import Head from 'next/head';
import Features from '../components/Features/Features';
import Header from '../components/Header/Header';
import Navbar from '../components/Navbar/Navbar';
import styles from '../styles/index.module.scss';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Navbar />
                <Header />
                <Features />
            </main>
        </div>
    );
}
